name: "Daily Build"
on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
      url:
        required: true
jobs:
  build-dependencies:
    name: Build Dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
    steps:
      - uses: actions/checkout@v4
      - name: Install required tools
        run: sudo apt update && sudo apt install pigz
      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          check-latest: true
      - name: Build Quarkus main
        run: |
          git clone --branch ${{ github.event.inputs.branch }} ${{ github.event.inputs.url }} && cd quarkus && ./mvnw -B -s .github/mvn-settings.xml clean install -Dquickly -Dno-test-modules -Prelocations
      - name: Tar Maven Repo
        shell: bash
        run: zip -r maven-repo.zip ~/.m2/repository
      - name: Persist Maven Repo
        uses: actions/upload-artifact@v4
        with:
          name: maven-repo
          path: maven-repo.zip
          retention-days: 1
